/*
 * chuk_check_core API
 * chuk_check_core API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.MatchResponse;
import org.openapitools.client.model.PlayerResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AttendResponse
 */
public class AttendResponseTest {
    private final AttendResponse model = new AttendResponse();

    /**
     * Model tests for AttendResponse
     */
    @Test
    public void testAttendResponse() {
        // TODO: test AttendResponse
    }

    /**
     * Test the property 'attendId'
     */
    @Test
    public void attendIdTest() {
        // TODO: test attendId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'updatedDate'
     */
    @Test
    public void updatedDateTest() {
        // TODO: test updatedDate
    }

    /**
     * Test the property 'player'
     */
    @Test
    public void playerTest() {
        // TODO: test player
    }

    /**
     * Test the property 'match'
     */
    @Test
    public void matchTest() {
        // TODO: test match
    }

}
