/*
 * chuk_check_core API
 * chuk_check_core API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.AttendDate;
import org.openapitools.client.model.MatchDate;
import org.openapitools.client.model.StadiumResponse;
import org.openapitools.client.model.TeamResponse;
import org.openapitools.client.model.VoteDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MatchResponse
 */
public class MatchResponseTest {
    private final MatchResponse model = new MatchResponse();

    /**
     * Model tests for MatchResponse
     */
    @Test
    public void testMatchResponse() {
        // TODO: test MatchResponse
    }

    /**
     * Test the property 'matchId'
     */
    @Test
    public void matchIdTest() {
        // TODO: test matchId
    }

    /**
     * Test the property 'otherTeamName'
     */
    @Test
    public void otherTeamNameTest() {
        // TODO: test otherTeamName
    }

    /**
     * Test the property 'home'
     */
    @Test
    public void homeTest() {
        // TODO: test home
    }

    /**
     * Test the property 'notice'
     */
    @Test
    public void noticeTest() {
        // TODO: test notice
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'matchDate'
     */
    @Test
    public void matchDateTest() {
        // TODO: test matchDate
    }

    /**
     * Test the property 'voteDate'
     */
    @Test
    public void voteDateTest() {
        // TODO: test voteDate
    }

    /**
     * Test the property 'attendDate'
     */
    @Test
    public void attendDateTest() {
        // TODO: test attendDate
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'updatedDate'
     */
    @Test
    public void updatedDateTest() {
        // TODO: test updatedDate
    }

    /**
     * Test the property 'team'
     */
    @Test
    public void teamTest() {
        // TODO: test team
    }

    /**
     * Test the property 'stadium'
     */
    @Test
    public void stadiumTest() {
        // TODO: test stadium
    }

}
