/*
 * chuk_check_core API
 * chuk_check_core API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MatchCreateRequest
 */
public class MatchCreateRequestTest {
    private final MatchCreateRequest model = new MatchCreateRequest();

    /**
     * Model tests for MatchCreateRequest
     */
    @Test
    public void testMatchCreateRequest() {
        // TODO: test MatchCreateRequest
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'stadiumId'
     */
    @Test
    public void stadiumIdTest() {
        // TODO: test stadiumId
    }

    /**
     * Test the property 'otherTeamName'
     */
    @Test
    public void otherTeamNameTest() {
        // TODO: test otherTeamName
    }

    /**
     * Test the property 'home'
     */
    @Test
    public void homeTest() {
        // TODO: test home
    }

    /**
     * Test the property 'notice'
     */
    @Test
    public void noticeTest() {
        // TODO: test notice
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'voteStartDate'
     */
    @Test
    public void voteStartDateTest() {
        // TODO: test voteStartDate
    }

    /**
     * Test the property 'voteEndDate'
     */
    @Test
    public void voteEndDateTest() {
        // TODO: test voteEndDate
    }

    /**
     * Test the property 'attendDeadlineDate'
     */
    @Test
    public void attendDeadlineDateTest() {
        // TODO: test attendDeadlineDate
    }

}
