/*
 * chuk_check_core API
 * chuk_check_core API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PlayerCreateRequest
 */
public class PlayerCreateRequestTest {
    private final PlayerCreateRequest model = new PlayerCreateRequest();

    /**
     * Model tests for PlayerCreateRequest
     */
    @Test
    public void testPlayerCreateRequest() {
        // TODO: test PlayerCreateRequest
    }

    /**
     * Test the property 'memberId'
     */
    @Test
    public void memberIdTest() {
        // TODO: test memberId
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'authority'
     */
    @Test
    public void authorityTest() {
        // TODO: test authority
    }

}
