/*
 * chuk_check_core API
 * chuk_check_core API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TeamCreateRequest
 */
public class TeamCreateRequestTest {
    private final TeamCreateRequest model = new TeamCreateRequest();

    /**
     * Model tests for TeamCreateRequest
     */
    @Test
    public void testTeamCreateRequest() {
        // TODO: test TeamCreateRequest
    }

    /**
     * Test the property 'regionId'
     */
    @Test
    public void regionIdTest() {
        // TODO: test regionId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
