/*
 * chuk_check_core API
 * chuk_check_core API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * MatchUpdateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-05T14:29:51.370708+09:00[Asia/Seoul]")
public class MatchUpdateRequest {
  public static final String SERIALIZED_NAME_STADIUM_ID = "stadiumId";
  @SerializedName(SERIALIZED_NAME_STADIUM_ID)
  private Long stadiumId;

  public static final String SERIALIZED_NAME_OTHER_TEAM_NAME = "otherTeamName";
  @SerializedName(SERIALIZED_NAME_OTHER_TEAM_NAME)
  private String otherTeamName;

  public static final String SERIALIZED_NAME_HOME = "home";
  @SerializedName(SERIALIZED_NAME_HOME)
  private Boolean home;

  public static final String SERIALIZED_NAME_NOTICE = "notice";
  @SerializedName(SERIALIZED_NAME_NOTICE)
  private String notice;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    CREATE("CREATE"),
    
    VOTE("VOTE"),
    
    ATTEND("ATTEND"),
    
    MATCH("MATCH"),
    
    FINISH("FINISH");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private OffsetDateTime startDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private OffsetDateTime endDate;

  public static final String SERIALIZED_NAME_VOTE_START_DATE = "voteStartDate";
  @SerializedName(SERIALIZED_NAME_VOTE_START_DATE)
  private OffsetDateTime voteStartDate;

  public static final String SERIALIZED_NAME_VOTE_END_DATE = "voteEndDate";
  @SerializedName(SERIALIZED_NAME_VOTE_END_DATE)
  private OffsetDateTime voteEndDate;

  public static final String SERIALIZED_NAME_ATTEND_DEADLINE_DATE = "attendDeadlineDate";
  @SerializedName(SERIALIZED_NAME_ATTEND_DEADLINE_DATE)
  private OffsetDateTime attendDeadlineDate;

  public MatchUpdateRequest() {
  }

  public MatchUpdateRequest stadiumId(Long stadiumId) {
    
    this.stadiumId = stadiumId;
    return this;
  }

   /**
   * Get stadiumId
   * @return stadiumId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getStadiumId() {
    return stadiumId;
  }


  public void setStadiumId(Long stadiumId) {
    this.stadiumId = stadiumId;
  }


  public MatchUpdateRequest otherTeamName(String otherTeamName) {
    
    this.otherTeamName = otherTeamName;
    return this;
  }

   /**
   * Get otherTeamName
   * @return otherTeamName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOtherTeamName() {
    return otherTeamName;
  }


  public void setOtherTeamName(String otherTeamName) {
    this.otherTeamName = otherTeamName;
  }


  public MatchUpdateRequest home(Boolean home) {
    
    this.home = home;
    return this;
  }

   /**
   * Get home
   * @return home
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHome() {
    return home;
  }


  public void setHome(Boolean home) {
    this.home = home;
  }


  public MatchUpdateRequest notice(String notice) {
    
    this.notice = notice;
    return this;
  }

   /**
   * Get notice
   * @return notice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNotice() {
    return notice;
  }


  public void setNotice(String notice) {
    this.notice = notice;
  }


  public MatchUpdateRequest status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public MatchUpdateRequest startDate(OffsetDateTime startDate) {
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getStartDate() {
    return startDate;
  }


  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }


  public MatchUpdateRequest endDate(OffsetDateTime endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getEndDate() {
    return endDate;
  }


  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }


  public MatchUpdateRequest voteStartDate(OffsetDateTime voteStartDate) {
    
    this.voteStartDate = voteStartDate;
    return this;
  }

   /**
   * Get voteStartDate
   * @return voteStartDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getVoteStartDate() {
    return voteStartDate;
  }


  public void setVoteStartDate(OffsetDateTime voteStartDate) {
    this.voteStartDate = voteStartDate;
  }


  public MatchUpdateRequest voteEndDate(OffsetDateTime voteEndDate) {
    
    this.voteEndDate = voteEndDate;
    return this;
  }

   /**
   * Get voteEndDate
   * @return voteEndDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getVoteEndDate() {
    return voteEndDate;
  }


  public void setVoteEndDate(OffsetDateTime voteEndDate) {
    this.voteEndDate = voteEndDate;
  }


  public MatchUpdateRequest attendDeadlineDate(OffsetDateTime attendDeadlineDate) {
    
    this.attendDeadlineDate = attendDeadlineDate;
    return this;
  }

   /**
   * Get attendDeadlineDate
   * @return attendDeadlineDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getAttendDeadlineDate() {
    return attendDeadlineDate;
  }


  public void setAttendDeadlineDate(OffsetDateTime attendDeadlineDate) {
    this.attendDeadlineDate = attendDeadlineDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchUpdateRequest matchUpdateRequest = (MatchUpdateRequest) o;
    return Objects.equals(this.stadiumId, matchUpdateRequest.stadiumId) &&
        Objects.equals(this.otherTeamName, matchUpdateRequest.otherTeamName) &&
        Objects.equals(this.home, matchUpdateRequest.home) &&
        Objects.equals(this.notice, matchUpdateRequest.notice) &&
        Objects.equals(this.status, matchUpdateRequest.status) &&
        Objects.equals(this.startDate, matchUpdateRequest.startDate) &&
        Objects.equals(this.endDate, matchUpdateRequest.endDate) &&
        Objects.equals(this.voteStartDate, matchUpdateRequest.voteStartDate) &&
        Objects.equals(this.voteEndDate, matchUpdateRequest.voteEndDate) &&
        Objects.equals(this.attendDeadlineDate, matchUpdateRequest.attendDeadlineDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stadiumId, otherTeamName, home, notice, status, startDate, endDate, voteStartDate, voteEndDate, attendDeadlineDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchUpdateRequest {\n");
    sb.append("    stadiumId: ").append(toIndentedString(stadiumId)).append("\n");
    sb.append("    otherTeamName: ").append(toIndentedString(otherTeamName)).append("\n");
    sb.append("    home: ").append(toIndentedString(home)).append("\n");
    sb.append("    notice: ").append(toIndentedString(notice)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    voteStartDate: ").append(toIndentedString(voteStartDate)).append("\n");
    sb.append("    voteEndDate: ").append(toIndentedString(voteEndDate)).append("\n");
    sb.append("    attendDeadlineDate: ").append(toIndentedString(attendDeadlineDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("stadiumId");
    openapiFields.add("otherTeamName");
    openapiFields.add("home");
    openapiFields.add("notice");
    openapiFields.add("status");
    openapiFields.add("startDate");
    openapiFields.add("endDate");
    openapiFields.add("voteStartDate");
    openapiFields.add("voteEndDate");
    openapiFields.add("attendDeadlineDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MatchUpdateRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (MatchUpdateRequest.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in MatchUpdateRequest is not found in the empty JSON string", MatchUpdateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MatchUpdateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MatchUpdateRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("otherTeamName") != null && !jsonObj.get("otherTeamName").isJsonNull()) && !jsonObj.get("otherTeamName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `otherTeamName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("otherTeamName").toString()));
      }
      if ((jsonObj.get("notice") != null && !jsonObj.get("notice").isJsonNull()) && !jsonObj.get("notice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notice").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MatchUpdateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MatchUpdateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MatchUpdateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MatchUpdateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<MatchUpdateRequest>() {
           @Override
           public void write(JsonWriter out, MatchUpdateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MatchUpdateRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MatchUpdateRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MatchUpdateRequest
  * @throws IOException if the JSON string is invalid with respect to MatchUpdateRequest
  */
  public static MatchUpdateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MatchUpdateRequest.class);
  }

 /**
  * Convert an instance of MatchUpdateRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

